name: Daily Cron Job

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run script
        run: |
          poetry run python3 data-scraper/scraper.py

      - name: push
        uses: actions-x/commit@v6
        with:
          name: GitHub Actions Autocommitter
          branch: daily-updates
          files: data-scraper/campuslabs_events_data.json
          force: true
