export const ORGANIZATIONS = [
  "African Students' Association",
  "Association of African-American Students",
  "Association of Asian, Pacific Islander, and Desi American",
  "The Brotherhood",
  "Caribbean Student Association",
  "Computing Opportunities for Students of Color",
  "Committee for Latinx Concerns",
  "DePauw China Connection",
  "DePauw First",
  "DePauw MAPS",
  "DePauw International Student Association",
  "Elite Precizion",
  "Exalt! Gospel Choir",
  "Feminista!",
  "The HEAT",
  "House of Opulence",
  "J-Club",
  "Ladies and Allies for Cross-Cultural Education",
  "La Fuerza Latina Latin Dance Group",
  "Native American & Indigenous People Association",
  "South Asian Student Society",
  "S.o.C.i.S. (Students of Color in STEM)",
  "Vietnamese Student Association",
  "The X-Cell Dance Team"
]
